config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/help', to: 'pages#help'


  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route("/") 
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end 

    def help
    end
    
end 

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new
        @std = Student.new
    end 
    
    def create
        @std = Student.new(student_params)
        if @std.save
            flash[:notice] = "todo was created"
            redirect_to student_path(@std)
        else
            render 'new'
        end
    end


    def show
        @std = Student.find(params[:id])
    end


    def edit
        @std = Student.find(params[:id])
    end

    def update
        @std = Student.find(params[:id])
        if @std.update(student_params)
            flash[:notice] = "student table is update"
            redirect_to student_path(@std)
        else
            render 'edit'
        end
    end

    def index
        @std = Student.all
    end

    def destroy
        @std = Student.find(params[:id])
        @std.destroy
        flash[:notice]= "column destroyed"
        redirect_to students_path
    end



    
    private

    def student_params
        params.require(:student).permit(:name, :description)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lecture2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name,msg|%>
      <ul>
        <li><%= msg%></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/help.html.erb
<h1>this a help page</h1>

app/views/pages/home.html.erb
<h1>this a home page</h1>

app/views/students/edit.html.erb
<h1>edit existingtodo</h1>



<%= form_for @std do |f|%>
    <p>
      <%= f.label :name%> <br>
      <%= f.text_field :name%>
    </p>

    <p>
      <%= f.label :description%> <br>
      <%= f.text_area :description%>
    </p>

    <p>
       <%= f.submit :update %>
    </p>
<% end %>  

<%= link_to "back to employees listing", students_path%>  

app/views/students/index.html.erb
<h1>listing all columns of a table</h1>

<%= link_to "create to create new columns", new_student_path%>

<table>
<tr>
   <th>Names</th>
   <th>Descriptions </th>
</tr>

<% @std.each do |s|%>
    <tr>
     <td><%= s.name%></td>
     <td><%= s.description%></td>
     <td><%= link_to "edit", edit_student_path(s)%></td>  
     <td><%= link_to "show", student_path(s)%></td>
     <td><%= link_to "delete", student_path(s), method: :delete, data: { "turbo-method": :delete }%></td>
    </tr>
<% end %>
</table>

app/views/students/new.html.erb
<h1>newww file</h1>
<% if @std.errors.any?%>
  <h1>The following errors preventted the actions</h1>
  <ul>
    <% @std.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @std do |f|%>
    <p>
      <%= f.label :name%> <br>
      <%= f.text_field :name%>
    </p>

    <p>
      <%= f.label :description%> <br>
      <%= f.text_area :description%>
    </p>

    <p>
       <%= f.submit :submit%>
    </p>
<% end %>

<%= link_to "back to employees listing", students_path%> 

app/views/students/show.html.erb
<h1>showing column</h1>

<p>
 name: <%= @std.name%>
</p>

<p>
  description: <%= @std.description%>
</p>

<%= link_to "edit the table", edit_student_path(@std)%>
<%= link_to "back to employees listing", students_path%> 